# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  check_codestyle:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Print working directory
      run: pwd
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check with black
      run: python -m black -q --check /src
